project:
  type: website
  output-dir: docs

website: 
  title: "Results"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - litreview.qmd
      - methods.qmd
      - findings.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

