project:
  type: website
  output-dir: docs

website:
  title: "Defining the suburbs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - literature.qmd
      - methods.qmd
      - results.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

