project:
  type: website
  output-dir: docs

website:
  title: "Suburban Delineations: Alternative ways to think about the suburban environment "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - LitReview.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

