project:
  type: website
  output-dir: docs

website: 
  title: "Diversity in the suburbs"
  navbar:
    left:
      - href: homepage.qmd
        text: Home
      - Testpage.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

