project:
  type: website
  output-dir: docs

website:
  title: "Defining the suburbs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - literature.qmd
      - methods.qmd
      - locations.qmd
      - results.qmd
      - references.qmd
format:
  html:
    theme: spacelab
    mainfont: arial
    fontsize: 1rem
    fontcolor: "#333333"
    linkcolor: "#809fff"
    monofont: courier new
    css: styles.css
    toc: true

editor: visual

