project:
  type: website
  output-dir: docs

website: 
  title: "Results"
  navbar:
    left:
      - href: homepage.qmd
        text: Home
      - href: litreview.qmd
        text: Diversity in the suburbs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

